#
# This file will be included by cmake/share/Headers.cmake
#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`.
# Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents are derived from the file locations

set( INCLUDE_DIRS
src
src/reflect
)

#
# contents selected with patternfile ??-header--private-generated-headers
#
set( PRIVATE_GENERATED_HEADERS
src/reflect/_mulle-fifo-include-private.h
)

#
# contents selected with patternfile ??-header--private-generic-headers
#
set( PRIVATE_GENERIC_HEADERS
src/include-private.h
)

#
# contents selected with patternfile ??-header--public-generated-headers
#
set( PUBLIC_GENERATED_HEADERS
src/reflect/_mulle-fifo-include.h
src/reflect/_mulle-fifo-include-public.h
src/reflect/_mulle-fifo-provide.h
)

#
# contents selected with patternfile ??-header--public-generic-headers
#
set( PUBLIC_GENERIC_HEADERS
src/include.h
)

#
# contents selected with patternfile ??-header--public-headers
#
set( PUBLIC_HEADERS
src/mulle-fifo.h
src/mulle--pointerfifo1024.h
src/mulle--pointerfifo128.h
src/mulle--pointerfifo16.h
src/mulle--pointerfifo2048.h
src/mulle--pointerfifo256.h
src/mulle--pointerfifo32.h
src/mulle--pointerfifo4096.h
src/mulle--pointerfifo4.h
src/mulle--pointerfifo512.h
src/mulle--pointerfifo64.h
src/mulle--pointerfifo8192.h
src/mulle--pointerfifo8.h
src/mulle-pointerfifo.h
)

